# Introduction to Statistics

## What is statistics?

### Early and modern definitions

- The word *statistics* has its roots in the Latin word *status* which means the state, and in the
middle of the 18th century was intended to mean
*collection, processing and use of data by the state*.
- With the rapid industrialisation of Europe in the first half of the 19th century, statistics
became established as a discipline. This led to the formation of the Royal Statistical Society,
the premier professional association of statisticians in the UK and also world-wide, in 1834.
- During this 19th century growth period, statistics acquired a new meaning as the *interpretation of data or methods of extracting information from data for decision making*. Thus
statistics has its modern meaning as the methods for
*collection, analysis and interpretation of data*.
- Indeed, the Oxford English Dictionary defines *statistics* as

> The practice or science of collecting and analysing numerical data in large quantities, especially for the purpose of inferring
proportions in a whole from those in a representative sample.

- Note that the word ‘state’ has gone from its definition. Instead, statistical methods are now
essential for **everyone** wanting to answer questions using data.

For example, will it rain tomorrow? Does eating red meat make us live longer? Is smoking
harmful during pregnancy? Is the new shampoo better than the old? Will the UK economy get
better after Brexit? At a more personal level: What degree classification will I get at graduation?
How long will I live for? What prospects do I have in the career I have chosen? How do I invest
my money to maximise the return? Will the stock market crash tomorrow?


### Uncertainty: the main obstacle to decision making

The main obstacle to answering the types of questions above is *uncertainty*, which means **lack of
one-to-one correspondence between cause and effect**. For example, having a diet of (well-cooked) red meat for a period of time is not going to kill me immediately. The effect of smoking
during pregnancy is difficult to judge because of the presence of other factors, e.g. diet and lifestyle;
such effects will not be known for a long time, e.g. at least until the birth. Thus it seems:

> **Uncertainty is the only certainty!**



### Statistics tames uncertainty

- It is clear that we may never be able to get to the bottom of every case to learn the full truth
and so will have to make a decision under uncertainty; thus mistakes cannot be avoided!
- If mistakes cannot be avoided, it is better to know how often we make mistakes (which
provides knowledge of the amount of uncertainty) by following a particular rule of decision
making.
- Such knowledge could be put to use in finding a rule of decision making which does not betray
us too often, or which minimises the frequency of wrong decisions, or which minimises the
loss due to wrong decisions.

Thus we have the equation 
\[\text{Uncertain knowledge} +
  \text{Knowledge of the extent of uncertainty in it} =
  \text{Usable knowledge.}\]
<!-- TODO: fix formatting -->


Researchers often make guesses about scientific quantities. For example, try to guess my age: 65
or 45? 
These predictions are meaningless without the associated uncertainties. Instead, appropriate
data collection and correct application of statistical methods may enable us to make statements
like: I am 97% certain that the correct age is between 47 and 54 years. Remember, 

> to guess is cheap, to guess incorrectly is expensive  
-- <cite>old Chinese proverb.</cite>
<!-- TODO: update ages -->


### Why should I study statistics as part of my degree?

- Studying statistics will equip you with the basic skills in data analysis and doing science with
data.
- A decent level of statistical knowledge is required no matter what branch of mathematics,
engineering, science and social science you will be studying.
- Learning statistical theories gives you the opportunity to practice your deductive mathematical skills on real life problems. In this way, you will improve at mathematical methods while
studying statistical methods.

>All knowledge is, in final analysis, history.  
>All sciences are, in the abstract, mathematics.  
>All judgements are, in their rationale, statistics.  
>-- <cite>Prof. C. R. Rao </cite>

### Lies, Damn Lies and Statistics?

Sometimes people say, "you can prove anything in statistics!" and many such jokes. Such remarks
bear testimony to the fact that often statistics and statistical methods are mis-quoted without
proper verification and robust justification. This is even more important in recent years of the global
pandemic when every day we have been showered with a deluge of numbers. The front and the back cover
of this booklet plot two pandemic related diagrams that we plan to discuss as we learn different
topics in this module.
Returning to the criticisms of statistics, admittedly and regretfully, statistics can be very much
mis-used and mis-interpreted. However, we statisticians argue:

- Every number is guilty unless proved innocent.
- Figures won't lie, but liars can figure!

Hence, although people may miss-use the tools of statistics, it is our duty to learn and sharpen the
those to develop scientifically robust and strong arguments.
As discussed before statistical methods are only viable tool whenever there is uncertainty in
decision making. In scientific investigations, statistics is an inevitable instrument in search of truth
when uncertainty cannot be totally removed from decision making. Of course, a statistical method
may not yield the best predictions in a very particular situation, but a systematic and robust
application of statistical methods will eventually win over pure guesses. For example, statistical
methods prove that cigarette smoking is bad for human health.


### What's in this module?

- **Chapter 1**: We will start with the basic statistics used in everyday life, e.g. mean, median,
mode, standard deviation, etc. Statistical analysis and report writing will be discussed. We
will also learn how to explore data using graphical methods.
  * For this we will use the R statistical package. R is freely available to download. Search
"download R" or go to: https://cran.r-project.org/. We will use it as a calculator
and also as a graphics package to explore data, perform statistical analysis, illustrate
theorems and calculate probabilities. You do not need to learn any programming language. You will be instructed to learn basic commands like: `2+2`; `mean(x)`; `plot(x,y)`.
  * In this module we will demonstrate using the R package. A nicer experience is provided
by the commercial, but still freely available, R Studio software. It is recommended that
you use that.
- **Chapter 2: Introduction to Probability**. We will define and interpret probability as a
measure of uncertainty. We will learn the rules of probability and then explore fun examples
of probability, e.g. the probability of winning the National Lottery.
- **Chapter 3: Random variables**. We will learn that the results of different random experiments lead to different random variables following distributions such as the binomial, and
normal. etc. We will learn their basic properties, e.g. mean and variance.
- **Chapter 4: Statistical Inference**. We will discuss basic ideas of statistical inference,
including techniques of point and interval estimation and hypothesis testing.

### Take home points:

- We apply statistical methods whenever there is uncertainty and complete enumeration is not
possible.
- This module will provide a very gentle introduction to statistics and probability together with
the software package R for data analysis.
- Statistical knowledge is essential for any scientific career in academia, industry and government.
- Read the New York Times article "For Today's Graduate, Just One Word: Statistics"
(search on Google).
- Watch the YouTube video "Joy of Statistics" before attending the next lecture.
